package exceptionHandling;

public class Test {
	
	//Abnormal termination of the programe
	
	public static void main(String[] args) {
		System.out.println("Testing");
		System.out.println("Testing");
		System.out.println("Testing");
		System.out.println("Testing");
		System.out.println("Testing");
		System.out.println(9/0);
		System.out.println("Testing");
		System.out.println("Testing");
		System.out.println("Testing");
		
		//Try
		//Catch
		//finally
		//throws
		//throw
		
		//Throws: Used for pass the Exception One method to another method
		//Throw: is used for User defined exceptions
		
	}

}
